# computational_phase_transition.py
"""
Computational Phase Transitions in the Silicon Manifold.

Formalizes the mapping from silicon state coordinates S = (n, d, ℓ, κ)
to computational complexity classes. Detects phase boundaries where
the set of physically realizable computations changes discontinuously.
"""

from __future__ import annotations

import numpy as np
from typing import Dict, List, Tuple, Optional, Set
from dataclasses import dataclass
from enum import Enum, auto
from scipy.special import expit  # sigmoid


# ─── Computational Complexity Classes ───

class ComputationalClass(Enum):
    """Computational complexity classes realizable in physical substrates."""
    CLASSICAL_P = auto()           # Deterministic polynomial time (NAND-based)
    QUANTUM_BQP = auto()           # Bounded-error quantum polynomial
    STOCHASTIC_BPP = auto()        # Bounded-error probabilistic polynomial
    CONTINUOUS_VARIABLE = auto()   # Continuous-variable computation (photonic)
    DEGRADED_NC0 = auto()          # Constant-depth with noise (defect-limited)
    MIXED_BQP_BPP = auto()         # Crossover regime (partial coherence)
    CHAOTIC = auto()               # No structured computation possible


@dataclass
class ComputationalGateSet:
    """The set of primitive operations a physical regime can implement."""
    name: str
    gates: Set[str]
    is_universal_classical: bool = False
    is_universal_quantum: bool = False
    max_circuit_depth: float = float('inf')
    error_rate: float = 0.0
    
    def closure_dimension(self) -> int:
        """
        Dimension of the function space generated by this gate set.
        Classical NAND: countable (all Boolean functions)
        Quantum {H, CNOT, T}: uncountable (all unitaries on 2^n states)
        """
        if self.is_universal_quantum:
            return float('inf')  # uncountably infinite
        elif self.is_universal_classical:
            return float('inf')  # countably infinite
        else:
            return len(self.gates) ** self.max_circuit_depth


# ─── Standard gate sets for each regime ───

GATE_SETS = {
    ComputationalClass.CLASSICAL_P: ComputationalGateSet(
        name="Classical Boolean",
        gates={"NAND"},
        is_universal_classical=True,
        max_circuit_depth=1e6,  # effectively unlimited
        error_rate=1e-15,
    ),
    ComputationalClass.QUANTUM_BQP: ComputationalGateSet(
        name="Quantum Clifford+T",
        gates={"H", "CNOT", "T"},
        is_universal_quantum=True,
        max_circuit_depth=1e4,  # limited by T₂
        error_rate=1e-4,
    ),
    ComputationalClass.STOCHASTIC_BPP: ComputationalGateSet(
        name="Stochastic Sampling",
        gates={"NAND", "RANDOM_BIT"},
        is_universal_classical=True,
        max_circuit_depth=1e5,
        error_rate=1e-2,
    ),
    ComputationalClass.CONTINUOUS_VARIABLE: ComputationalGateSet(
        name="Linear Optical",
        gates={"BEAMSPLITTER", "PHASE_SHIFT", "SQUEEZING"},
        is_universal_quantum=True,
        max_circuit_depth=1e3,
        error_rate=1e-3,
    ),
    ComputationalClass.DEGRADED_NC0: ComputationalGateSet(
        name="Degraded Constant-Depth",
        gates={"NAND"},
        is_universal_classical=False,
        max_circuit_depth=10,  # severely limited by defects
        error_rate=0.1,
    ),
    ComputationalClass.MIXED_BQP_BPP: ComputationalGateSet(
        name="Mixed Quantum-Classical",
        gates={"H", "CNOT", "T", "RANDOM_BIT"},
        is_universal_quantum=False,  # lost full quantum universality
        is_universal_classical=True,
        max_circuit_depth=1e3,
        error_rate=5e-3,
    ),
    ComputationalClass.CHAOTIC: ComputationalGateSet(
        name="Chaotic (No Structured Computation)",
        gates=set(),
        max_circuit_depth=0,
        error_rate=1.0,
    ),
}


@dataclass
class SiliconState:
    """Minimal self-contained silicon state used by this module.

    The repository copy of this file referenced an external `silicon_state`
    module that is not present in the current tree. Keeping a compact local
    representation here avoids that broken dependency and makes the phase-diagram
    demo importable again.
    """

    n: float
    d: float
    l: float
    k: Dict[str, float]

    def regime_weights(self, temperature: float = 0.1) -> Dict[str, float]:
        """Compute smooth regime weights from the silicon coordinates.

        The weights are normalized so downstream classification can treat them as
        mixture coefficients over the named computational regimes.
        """
        log_n = np.log10(max(self.n, 1.0))
        optical = float(self.k.get("optical", 0.0))
        thermal = float(self.k.get("thermal", 0.0))
        coherent = float(self.k.get("coherent", 0.0))
        electrical = float(self.k.get("electrical", 0.0))
        mechanical = float(self.k.get("mechanical", 0.0))

        semiconductor = (
            expit(4.0 - abs(log_n - 16.5) * 2.0)
            * expit((0.25 - self.d) * 10.0)
            * (0.5 + 0.5 * electrical)
        )
        metallic = expit((log_n - 19.0) * 3.0) * (0.5 + 0.5 * electrical)
        quantum = (
            expit((coherent - 0.25) * 8.0)
            * expit((0.18 - self.d) * 14.0)
            * expit((1.2 - self.l) * 4.0)
            * expit((0.18 - temperature) * 12.0)
        )
        photonic = (0.2 + optical) * expit((self.l - 1.2) * 3.0)
        defect_dominated = expit((self.d - 0.35) * 10.0) * (0.6 + 0.4 * thermal)
        mechanical_regime = (0.2 + mechanical) * expit((self.l - 2.0) * 2.5)

        raw_weights = {
            "semiconductor": max(0.0, semiconductor),
            "metallic": max(0.0, metallic),
            "quantum": max(0.0, quantum),
            "photonic": max(0.0, photonic),
            "defect_dominated": max(0.0, defect_dominated),
            "mechanical": max(0.0, mechanical_regime),
        }

        total = sum(raw_weights.values())
        if total <= 0:
            return {name: 0.0 for name in raw_weights}
        return {name: value / total for name, value in raw_weights.items()}


# ─── Core: Silicon State → Computational Class mapping ───

@dataclass
class ComputationalPhase:
    """A point in the computational phase diagram."""
    silicon_state: 'SiliconState'  # forward reference
    comp_class: ComputationalClass
    confidence: float               # 0-1, how strongly classified
    coherence_volume: float          # order parameter
    gate_set: ComputationalGateSet
    phase_boundary_distance: float   # distance to nearest transition
    
    def is_near_transition(self, threshold: float = 0.1) -> bool:
        """Is this point close to a computational phase boundary?"""
        return self.phase_boundary_distance < threshold
    
    def susceptibility(self) -> float:
        """
        Computational susceptibility: how much does computational power
        change with a small perturbation to the silicon state?
        High near phase boundaries (diverges at transition).
        """
        return 1.0 / (self.phase_boundary_distance + 1e-6)


def classify_computational_phase(
    silicon_state: 'SiliconState',
    temperature: float = 0.1,
) -> ComputationalPhase:
    """
    Maps a silicon state vector to its computational complexity class.
    
    This is the central function that realizes the computational phase
    transition framework. It takes the continuous silicon coordinates
    and produces a discrete computational classification.
    
    The mapping is:
    1. Compute regime weights (continuous)
    2. Identify the computational class for each regime
    3. Compute order parameter (coherence volume)
    4. Measure distance to nearest phase boundary
    5. Return classified phase with confidence
    """
    
    # Get continuous regime weights
    regime_weights = silicon_state.regime_weights(temperature=temperature)
    
    # Map regimes to computational classes
    regime_to_comp = {
        "semiconductor": ComputationalClass.CLASSICAL_P,
        "metallic": ComputationalClass.STOCHASTIC_BPP,
        "quantum": ComputationalClass.QUANTUM_BQP,
        "photonic": ComputationalClass.CONTINUOUS_VARIABLE,
        "defect_dominated": ComputationalClass.DEGRADED_NC0,
        "mechanical": ComputationalClass.CLASSICAL_P,  # can support classical
    }
    
    # ── Coherence volume (the order parameter) ──
    # V_coh = effective number of qubits that can be entangled
    # before decoherence destroys the quantum state
    
    # Base coherence from low defect density
    d_crit = 0.3  # critical defect density
    defect_factor = np.exp(-silicon_state.d / d_crit)
    
    # Dimensionality factor
    ell_0 = 2.0  # reference dimension
    alpha = 1.5  # scaling exponent
    dim_factor = (silicon_state.l / ell_0) ** alpha
    
    # Thermal decoherence
    coherent_coupling = silicon_state.k.get("coherent", 0)
    thermal_coupling = silicon_state.k.get("thermal", 0)
    if thermal_coupling > 1e-10:
        thermal_factor = max(0, 1 - thermal_coupling / (coherent_coupling + thermal_coupling + 1e-10))
    else:
        thermal_factor = 1.0
    
    # Optical coupling enables quantum photonic computation
    optical_coupling = silicon_state.k.get("optical", 0)
    optical_factor = 1.0 + optical_coupling * 0.5
    
    coherence_volume = defect_factor * dim_factor * thermal_factor * optical_factor
    
    # ── Determine dominant computational class ──
    # Weighted by regime weights and coherence volume
    
    class_scores = {}
    for regime, weight in regime_weights.items():
        comp_class = regime_to_comp.get(regime)
        if comp_class:
            # Quantum class requires coherence volume > 1
            if comp_class == ComputationalClass.QUANTUM_BQP:
                if coherence_volume < 1.0:
                    # Degraded to mixed class
                    class_scores[ComputationalClass.MIXED_BQP_BPP] = (
                        class_scores.get(ComputationalClass.MIXED_BQP_BPP, 0) + weight
                    )
                else:
                    class_scores[comp_class] = class_scores.get(comp_class, 0) + weight
            else:
                class_scores[comp_class] = class_scores.get(comp_class, 0) + weight
    
    # Handle empty case
    if not class_scores:
        dominant_class = ComputationalClass.CHAOTIC
        confidence = 0.0
    else:
        dominant_class = max(class_scores, key=class_scores.get)
        total_score = sum(class_scores.values())
        confidence = class_scores[dominant_class] / total_score if total_score > 0 else 0
    
    # ── Distance to nearest phase boundary ──
    # A phase boundary is where: coherence_volume ≈ 1, or
    # where two computational classes have nearly equal scores
    
    # Coherence boundary
    dist_to_coherence_boundary = abs(coherence_volume - 1.0)
    
    # Regime competition boundary
    sorted_scores = sorted(class_scores.values(), reverse=True)
    if len(sorted_scores) >= 2:
        score_gap = sorted_scores[0] - sorted_scores[1]
        dist_to_regime_boundary = score_gap / (sorted_scores[0] + 1e-10)
    else:
        dist_to_regime_boundary = 1.0
    
    phase_boundary_distance = min(dist_to_coherence_boundary, dist_to_regime_boundary)
    
    # Get gate set
    gate_set = GATE_SETS.get(dominant_class, GATE_SETS[ComputationalClass.CHAOTIC])
    
    return ComputationalPhase(
        silicon_state=silicon_state,
        comp_class=dominant_class,
        confidence=confidence,
        coherence_volume=coherence_volume,
        gate_set=gate_set,
        phase_boundary_distance=phase_boundary_distance,
    )


# ─── Phase transition detection ───

@dataclass
class PhaseTransition:
    """A detected computational phase transition between two states."""
    start_phase: ComputationalPhase
    end_phase: ComputationalPhase
    transition_type: str  # 'first_order', 'continuous', 'crossover'
    order_parameter_jump: float
    susceptibility_peak: float
    silicon_path: List[Dict]  # intermediate states along the transition


def detect_phase_transition(
    silicon_trajectory: List['SiliconState'],
    temperature: float = 0.1,
    threshold: float = 0.05,
) -> List[PhaseTransition]:
    """
    Scan a trajectory through silicon phase space for computational
    phase transitions.
    
    A transition is detected when:
    1. The computational class changes between consecutive points
    2. OR the coherence volume crosses the critical threshold (V_coh = 1)
    3. OR either endpoint lies within `threshold` of a phase boundary
    """
    
    transitions = []
    
    for i in range(len(silicon_trajectory) - 1):
        phase_start = classify_computational_phase(
            silicon_trajectory[i], temperature
        )
        phase_end = classify_computational_phase(
            silicon_trajectory[i + 1], temperature
        )
        
        class_change = phase_start.comp_class != phase_end.comp_class
        coherence_crossing = (
            (phase_start.coherence_volume - 1.0) * 
            (phase_end.coherence_volume - 1.0) < 0
        )
        near_boundary = (
            min(
                phase_start.phase_boundary_distance,
                phase_end.phase_boundary_distance,
            ) < threshold
        )
        
        if class_change or coherence_crossing or near_boundary:
            # Classify transition type
            order_jump = abs(phase_end.coherence_volume - phase_start.coherence_volume)
            susc_peak = max(phase_start.susceptibility(), phase_end.susceptibility())
            
            if order_jump > 0.5:
                trans_type = "first_order"
            elif order_jump > 0.1:
                trans_type = "continuous"
            else:
                trans_type = "crossover"
            
            transitions.append(PhaseTransition(
                start_phase=phase_start,
                end_phase=phase_end,
                transition_type=trans_type,
                order_parameter_jump=order_jump,
                susceptibility_peak=susc_peak,
                silicon_path=[
                    {"n": silicon_trajectory[i].n, 
                     "d": silicon_trajectory[i].d,
                     "l": silicon_trajectory[i].l}
                ],
            ))
    
    return transitions


# ─── Computational expressivity measurement ───

def measure_expressivity(
    phase: ComputationalPhase,
    test_problems: List[str] = None,
) -> Dict[str, bool]:
    """
    For a given computational phase, determine which benchmark
    problems are solvable given the gate set and error rate.
    
    This is a practical measure of computational power that
    can be compared across phases.
    """
    
    if test_problems is None:
        test_problems = [
            "factoring_21",        # 3×7, trivial classically, BQP advantage
            "search_unsorted_8",   # Grover on 3 qubits
            "boolean_sat_3var",    # 3-SAT with 3 variables
            "fourier_transform_4", # QFT on 4 states
            "random_sampling_100", # 100-bit stochastic sampling
        ]
    
    capabilities = {}
    gate_set = phase.gate_set
    error_rate = phase.gate_set.error_rate
    
    for problem in test_problems:
        if problem == "factoring_21":
            # Requires quantum Fourier transform + modular exponentiation
            capabilities[problem] = (
                gate_set.is_universal_quantum and 
                phase.coherence_volume >= 3 and
                error_rate < 0.01
            )
        
        elif problem == "search_unsorted_8":
            # Grover: requires Hadamard + oracle + diffusion
            capabilities[problem] = (
                gate_set.is_universal_quantum and
                phase.coherence_volume >= 1 and
                error_rate < 0.05
            )
        
        elif problem == "boolean_sat_3var":
            # Classical SAT: requires NAND universality
            capabilities[problem] = (
                gate_set.is_universal_classical and
                gate_set.max_circuit_depth >= 100 and
                error_rate < 0.1
            )
        
        elif problem == "fourier_transform_4":
            capabilities[problem] = (
                gate_set.is_universal_quantum and
                phase.coherence_volume >= 2
            )
        
        elif problem == "random_sampling_100":
            capabilities[problem] = (
                error_rate < 0.05 and
                gate_set.max_circuit_depth >= 100
            )
    
    return capabilities


# ─── The computational phase diagram ───

def compute_phase_diagram(
    n_range: Tuple[float, float],
    d_range: Tuple[float, float],
    resolution: int = 100,
    l_fixed: float = 3.0,
    k_fixed: Dict[str, float] = None,
) -> Tuple[np.ndarray, np.ndarray, np.ndarray, Dict[int, ComputationalClass]]:
    """
    Compute the computational phase diagram over the (n, d) plane.
    
    Returns:
        class_map: (resolution, resolution) integer array of computational classes
        coherence_map: (resolution, resolution) coherence volume array
        susceptibility_map: (resolution, resolution) susceptibility array
        int_to_class: mapping from integer labels back to enum values
    """
    
    if k_fixed is None:
        k_fixed = {"electrical": 0.5, "optical": 0.0, "thermal": 0.1, 
                   "mechanical": 0.0, "coherent": 0.4}
    
    n_vals = np.logspace(np.log10(n_range[0]), np.log10(n_range[1]), resolution)
    d_vals = np.linspace(d_range[0], d_range[1], resolution)
    
    class_map = np.zeros((resolution, resolution), dtype=int)
    coherence_map = np.zeros((resolution, resolution))
    susceptibility_map = np.zeros((resolution, resolution))
    
    class_to_int = {}
    int_to_class = {}
    
    for i, d in enumerate(d_vals):
        for j, n in enumerate(n_vals):
            S = SiliconState(n=n, d=d, l=l_fixed, k=k_fixed.copy())
            phase = classify_computational_phase(S)
            
            if phase.comp_class not in class_to_int:
                idx = len(class_to_int)
                class_to_int[phase.comp_class] = idx
                int_to_class[idx] = phase.comp_class
            
            class_map[i, j] = class_to_int[phase.comp_class]
            coherence_map[i, j] = phase.coherence_volume
            susceptibility_map[i, j] = phase.susceptibility()
    
    return class_map, coherence_map, susceptibility_map, int_to_class


# ─── Visualization ───

def plot_computational_phase_diagram(
    class_map: np.ndarray,
    coherence_map: np.ndarray,
    susceptibility_map: np.ndarray,
    int_to_class: Dict[int, ComputationalClass],
    n_range: Tuple[float, float],
    d_range: Tuple[float, float],
    save_path: Optional[str] = None,
):
    """Visualize the computational phase diagram with phase boundaries."""
    import matplotlib.pyplot as plt
    from matplotlib.colors import ListedColormap, BoundaryNorm
    
    fig, axes = plt.subplots(1, 3, figsize=(18, 5))
    
    # Color map for computational classes
    class_colors = {
        ComputationalClass.CLASSICAL_P: '#2E86AB',
        ComputationalClass.QUANTUM_BQP: '#F18F01',
        ComputationalClass.STOCHASTIC_BPP: '#A23B72',
        ComputationalClass.CONTINUOUS_VARIABLE: '#C73E1D',
        ComputationalClass.DEGRADED_NC0: '#6B4D57',
        ComputationalClass.MIXED_BQP_BPP: '#9B5DE5',
        ComputationalClass.CHAOTIC: '#333333',
    }
    
    colors = [class_colors.get(int_to_class.get(i, ComputationalClass.CHAOTIC), '#888') 
              for i in range(len(int_to_class))]
    cmap = ListedColormap(colors)
    
    n_vals = np.logspace(np.log10(n_range[0]), np.log10(n_range[1]), class_map.shape[1])
    d_vals = np.linspace(d_range[0], d_range[1], class_map.shape[0])
    
    # Panel 1: Computational class
    ax1 = axes[0]
    im1 = ax1.pcolormesh(n_vals, d_vals, class_map, cmap=cmap, shading='auto')
    ax1.set_xscale('log')
    ax1.set_xlabel('Carrier density n (cm⁻³)')
    ax1.set_ylabel('Defect density d')
    ax1.set_title('Computational Phase Diagram')
    
    # Add legend
    legend_patches = [
        plt.Rectangle((0,0),1,1, facecolor=class_colors[c], edgecolor='black')
        for c in int_to_class.values()
    ]
    ax1.legend(legend_patches, [c.name for c in int_to_class.values()],
              loc='upper left', fontsize=6, ncol=2)
    
    # Panel 2: Coherence volume (order parameter)
    ax2 = axes[1]
    im2 = ax2.pcolormesh(n_vals, d_vals, coherence_map, cmap='RdYlBu_r', 
                         shading='auto', vmin=0, vmax=5)
    ax2.set_xscale('log')
    ax2.set_xlabel('Carrier density n (cm⁻³)')
    ax2.set_ylabel('Defect density d')
    ax2.set_title('Coherence Volume V_coh (Order Parameter)')
    ax2.axhline(y=0.3, color='black', linestyle='--', alpha=0.5, 
                label='d_crit (defect boundary)')
    plt.colorbar(im2, ax=ax2, label='V_coh')
    
    # Panel 3: Computational susceptibility
    ax3 = axes[2]
    # Log scale for susceptibility to show peaks
    im3 = ax3.pcolormesh(n_vals, d_vals, np.log10(susceptibility_map + 1),
                         cmap='hot', shading='auto')
    ax3.set_xscale('log')
    ax3.set_xlabel('Carrier density n (cm⁻³)')
    ax3.set_ylabel('Defect density d')
    ax3.set_title('Computational Susceptibility χ_comp\n(bright = phase boundary)')
    plt.colorbar(im3, ax=ax3, label='log₁₀(χ_comp + 1)')
    
    plt.tight_layout()
    
    if save_path:
        plt.savefig(save_path, dpi=150, bbox_inches='tight', facecolor='white')
    
    return fig


# ─── Benchmark: Compare computational power across phases ───

def benchmark_computational_phases(
    phases: List[ComputationalPhase],
):
    """
    Compare the computational capabilities of different phases.
    """
    import pandas as pd
    
    test_problems = [
        "factoring_21",
        "search_unsorted_8", 
        "boolean_sat_3var",
        "fourier_transform_4",
        "random_sampling_100",
    ]
    
    results = []
    for phase in phases:
        capabilities = measure_expressivity(phase, test_problems)
        row = {
            "Class": phase.comp_class.name,
            "Confidence": f"{phase.confidence:.2f}",
            "V_coh": f"{phase.coherence_volume:.2f}",
            "χ_comp": f"{phase.susceptibility():.1f}",
            "Near boundary": phase.is_near_transition(),
        }
        row.update(capabilities)
        results.append(row)
    
    return pd.DataFrame(results)


# ─── Demo ───

if __name__ == "__main__":
    print("=" * 70)
    print("COMPUTATIONAL PHASE TRANSITIONS IN SILICON MANIFOLDS")
    print("=" * 70)
    
    # Create states across the phase diagram
    test_states = [
        ("Semiconductor (CMOS)", SiliconState(
            n=1e16, d=0.02, l=3.0,
            k={"electrical": 0.8, "optical": 0.0, "thermal": 0.1, 
               "mechanical": 0.0, "coherent": 0.1}
        )),
        ("Quantum confinement", SiliconState(
            n=1e17, d=0.01, l=0.5,
            k={"electrical": 0.2, "optical": 0.1, "thermal": 0.05,
               "mechanical": 0.05, "coherent": 0.6}
        )),
        ("Metallic breakdown", SiliconState(
            n=1e21, d=0.4, l=3.0,
            k={"electrical": 0.9, "optical": 0.0, "thermal": 0.1,
               "mechanical": 0.0, "coherent": 0.0}
        )),
        ("Defect-dominated", SiliconState(
            n=1e16, d=0.75, l=2.5,
            k={"electrical": 0.3, "optical": 0.0, "thermal": 0.4,
               "mechanical": 0.2, "coherent": 0.1}
        )),
        ("Near decoherence boundary", SiliconState(
            n=5e17, d=0.15, l=1.5,
            k={"electrical": 0.3, "optical": 0.1, "thermal": 0.3,
               "mechanical": 0.1, "coherent": 0.2}
        )),
    ]
    
    phases = []
    for name, state in test_states:
        phase = classify_computational_phase(state)
        phases.append(phase)
        
        print(f"\n{name}:")
        print(f"  Class:        {phase.comp_class.name}")
        print(f"  Confidence:   {phase.confidence:.3f}")
        print(f"  V_coh:        {phase.coherence_volume:.3f}")
        print(f"  χ_comp:       {phase.susceptibility():.1f}")
        print(f"  Near boundary: {phase.is_near_transition()}")
        print(f"  Gate set:     {phase.gate_set.name}")
        print(f"  Max depth:    {phase.gate_set.max_circuit_depth:.0f}")
        
        capabilities = measure_expressivity(phase)
        print(f"  Capabilities:")
        for problem, capable in capabilities.items():
            print(f"    {problem}: {'✓' if capable else '✗'}")
    
    # Compute full phase diagram
    print("\n\nComputing full phase diagram...")
    class_map, coh_map, susc_map, int_to_class = compute_phase_diagram(
        n_range=(1e14, 1e22),
        d_range=(0.0, 1.0),
        resolution=100,
    )
    
    print(f"  Phase diagram: {class_map.shape}")
    print(f"  Classes found: {[c.name for c in int_to_class.values()]}")
    
    # Find phase boundaries (where susceptibility > threshold)
    boundary_pixels = np.sum(susc_map > np.percentile(susc_map, 95))
    print(f"  Phase boundary pixels (top 5% χ): {boundary_pixels}")
    
    # Visualize
    try:
        fig = plot_computational_phase_diagram(
            class_map, coh_map, susc_map, int_to_class,
            n_range=(1e14, 1e22), d_range=(0.0, 1.0),
            save_path="computational_phase_diagram.png"
        )
        print("  → Saved: computational_phase_diagram.png")
    except Exception as e:
        print(f"  Visualization skipped: {e}")
    
    print("\n" + "=" * 70)
